colorscheme ron
set backup
set diffexpr=MyDiff()
set fileformat=unix
set helplang=ko
set backspace=indent,eol,start
set selection=exclusive
set selectmode=mouse,key
set whichwrap=b,s,<,>,[,]
set history=1000
set hlsearch
set incsearch
set langnoremap
set nrformats=bin,hex
set ruler
set scroll=25
set scrolloff=5
set notextmode
set ttimeout
set ttimeoutlen=100
set ttyfast
set undofile
set wildmenu
set smartindent
set autoindent
set nu
